/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EstatisticasRouteImport } from './routes/estatisticas'
import { Route as EstudosRouteImport } from './routes/estudos'
import { Route as EvolucaoRouteImport } from './routes/evolucao'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as IcmRouteImport } from './routes/icm'
import { Route as MaosRouteImport } from './routes/maos'
import { Route as PushFoldRouteImport } from './routes/push-fold'
import { Route as ReplayerRouteImport } from './routes/replayer'
import { Route as SessoesRouteImport } from './routes/sessoes'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as PushFoldIndexRouteImport } from './routes/push-fold.index'
import { Route as PushFoldTreinarRouteImport } from './routes/push-fold.treinar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatisticasRoute = EstatisticasRouteImport.update({
  id: '/estatisticas',
  path: '/estatisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudosRoute = EstudosRouteImport.update({
  id: '/estudos',
  path: '/estudos',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucaoRoute = EvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const IcmRoute = IcmRouteImport.update({
  id: '/icm',
  path: '/icm',
  getParentRoute: () => rootRouteImport,
} as any)
const MaosRoute = MaosRouteImport.update({
  id: '/maos',
  path: '/maos',
  getParentRoute: () => rootRouteImport,
} as any)
const PushFoldRoute = PushFoldRouteImport.update({
  id: '/push-fold',
  path: '/push-fold',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayerRoute = ReplayerRouteImport.update({
  id: '/replayer',
  path: '/replayer',
  getParentRoute: () => rootRouteImport,
} as any)
const SessoesRoute = SessoesRouteImport.update({
  id: '/sessoes',
  path: '/sessoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const PushFoldIndexRoute = PushFoldIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PushFoldRoute,
} as any)
const PushFoldTreinarRoute = PushFoldTreinarRouteImport.update({
  id: '/treinar',
  path: '/treinar',
  getParentRoute: () => PushFoldRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estatisticas': typeof EstatisticasRoute
  '/estudos': typeof EstudosRoute
  '/evolucao': typeof EvolucaoRoute
  '/favoritos': typeof FavoritosRoute
  '/icm': typeof IcmRoute
  '/maos': typeof MaosRoute
  '/push-fold': typeof PushFoldRouteWithChildren
  '/replayer': typeof ReplayerRoute
  '/sessoes': typeof SessoesRoute
  '/tags': typeof TagsRoute
  '/push-fold/treinar': typeof PushFoldTreinarRoute
  '/push-fold/': typeof PushFoldIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estatisticas': typeof EstatisticasRoute
  '/estudos': typeof EstudosRoute
  '/evolucao': typeof EvolucaoRoute
  '/favoritos': typeof FavoritosRoute
  '/icm': typeof IcmRoute
  '/maos': typeof MaosRoute
  '/replayer': typeof ReplayerRoute
  '/sessoes': typeof SessoesRoute
  '/tags': typeof TagsRoute
  '/push-fold/treinar': typeof PushFoldTreinarRoute
  '/push-fold': typeof PushFoldIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coach': typeof CoachRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/estatisticas': typeof EstatisticasRoute
  '/estudos': typeof EstudosRoute
  '/evolucao': typeof EvolucaoRoute
  '/favoritos': typeof FavoritosRoute
  '/icm': typeof IcmRoute
  '/maos': typeof MaosRoute
  '/push-fold': typeof PushFoldRouteWithChildren
  '/replayer': typeof ReplayerRoute
  '/sessoes': typeof SessoesRoute
  '/tags': typeof TagsRoute
  '/push-fold/treinar': typeof PushFoldTreinarRoute
  '/push-fold/': typeof PushFoldIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coach'
    | '/configuracoes'
    | '/estatisticas'
    | '/estudos'
    | '/evolucao'
    | '/favoritos'
    | '/icm'
    | '/maos'
    | '/push-fold'
    | '/replayer'
    | '/sessoes'
    | '/tags'
    | '/push-fold/treinar'
    | '/push-fold/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coach'
    | '/configuracoes'
    | '/estatisticas'
    | '/estudos'
    | '/evolucao'
    | '/favoritos'
    | '/icm'
    | '/maos'
    | '/replayer'
    | '/sessoes'
    | '/tags'
    | '/push-fold/treinar'
    | '/push-fold'
  id:
    | '__root__'
    | '/'
    | '/coach'
    | '/configuracoes'
    | '/estatisticas'
    | '/estudos'
    | '/evolucao'
    | '/favoritos'
    | '/icm'
    | '/maos'
    | '/push-fold'
    | '/replayer'
    | '/sessoes'
    | '/tags'
    | '/push-fold/treinar'
    | '/push-fold/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoachRoute: typeof CoachRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EstatisticasRoute: typeof EstatisticasRoute
  EstudosRoute: typeof EstudosRoute
  EvolucaoRoute: typeof EvolucaoRoute
  FavoritosRoute: typeof FavoritosRoute
  IcmRoute: typeof IcmRoute
  MaosRoute: typeof MaosRoute
  PushFoldRoute: typeof PushFoldRouteWithChildren
  ReplayerRoute: typeof ReplayerRoute
  SessoesRoute: typeof SessoesRoute
  TagsRoute: typeof TagsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatisticas': {
      id: '/estatisticas'
      path: '/estatisticas'
      fullPath: '/estatisticas'
      preLoaderRoute: typeof EstatisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudos': {
      id: '/estudos'
      path: '/estudos'
      fullPath: '/estudos'
      preLoaderRoute: typeof EstudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucao': {
      id: '/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof EvolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icm': {
      id: '/icm'
      path: '/icm'
      fullPath: '/icm'
      preLoaderRoute: typeof IcmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maos': {
      id: '/maos'
      path: '/maos'
      fullPath: '/maos'
      preLoaderRoute: typeof MaosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/push-fold': {
      id: '/push-fold'
      path: '/push-fold'
      fullPath: '/push-fold'
      preLoaderRoute: typeof PushFoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replayer': {
      id: '/replayer'
      path: '/replayer'
      fullPath: '/replayer'
      preLoaderRoute: typeof ReplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessoes': {
      id: '/sessoes'
      path: '/sessoes'
      fullPath: '/sessoes'
      preLoaderRoute: typeof SessoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/push-fold/': {
      id: '/push-fold/'
      path: '/'
      fullPath: '/push-fold/'
      preLoaderRoute: typeof PushFoldIndexRouteImport
      parentRoute: typeof PushFoldRoute
    }
    '/push-fold/treinar': {
      id: '/push-fold/treinar'
      path: '/treinar'
      fullPath: '/push-fold/treinar'
      preLoaderRoute: typeof PushFoldTreinarRouteImport
      parentRoute: typeof PushFoldRoute
    }
  }
}

interface PushFoldRouteChildren {
  PushFoldTreinarRoute: typeof PushFoldTreinarRoute
  PushFoldIndexRoute: typeof PushFoldIndexRoute
}

const PushFoldRouteChildren: PushFoldRouteChildren = {
  PushFoldTreinarRoute: PushFoldTreinarRoute,
  PushFoldIndexRoute: PushFoldIndexRoute,
}

const PushFoldRouteWithChildren = PushFoldRoute._addFileChildren(
  PushFoldRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoachRoute: CoachRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EstatisticasRoute: EstatisticasRoute,
  EstudosRoute: EstudosRoute,
  EvolucaoRoute: EvolucaoRoute,
  FavoritosRoute: FavoritosRoute,
  IcmRoute: IcmRoute,
  MaosRoute: MaosRoute,
  PushFoldRoute: PushFoldRouteWithChildren,
  ReplayerRoute: ReplayerRoute,
  SessoesRoute: SessoesRoute,
  TagsRoute: TagsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
